## set base image
FROM node:20-alpine

# ⭐ 'ARG' 예약어를 통해 인자로 전달 받아야 한다.
ARG DISCORD_TOKEN 
ENV DISCORD_TOKEN=${DISCORD_TOKEN}

ARG VOICE_CHANNEL 
ENV VOICE_CHANNEL=${VOICE_CHANNEL}

ARG DISCORD_CLIENT_ID 
ENV DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

ARG DISCORD_SERVER_ID 
ENV DISCORD_SERVER_ID=${DISCORD_SERVER_ID}

ARG SUPABASE_URL 
ENV SUPABASE_URL=${SUPABASE_URL}

ARG SUPABASE_API_KEY 
ENV SUPABASE_API_KEY=${SUPABASE_API_KEY}

## set working directory
WORKDIR /usr/src/app

## COPY necessory files
COPY package*.json ./ 

## Install necessory packages
RUN npm ci

COPY . .


CMD ["npm", "run","start"]