name: Create and publish a Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.GAR_REGISTRY }}
  IMAGE_NAME: image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
