name: Create and publish a Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.GAR_REGISTRY }}
  IMAGE_NAME: image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          ##
          #build-args: |
          #  "DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}"
          push: true
          tags: ${{ steps.meta.outputs.labels }}
          labels: ${{ steps.meta.outputs.labels }}
